# -*- coding: utf-8 -*-
"""ProgrammaticPrompting1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10USwjwaJ-1J-I_2igKIbJ-GdMDWlHKRU
"""

#!!pip install litellm

# Important!!!
#
# <---- Set your 'OPENAI_API_KEY' as a secret over there with the "key" icon
#
#
from dotenv import load_dotenv
import os
from litellm import completion
from typing import List, Dict
#from google.colab import userdata
#api_key = userdata.get('OPENAI_API_KEY')


load_dotenv()
api_key = os.getenv("OPENAI_API_KEY")



def generate_response(messages: List[Dict]) -> str:
    """Call LLM to get response"""
    response = completion(
        model="openai/gpt-4.1-mini",
        messages=messages,
        max_tokens=1024
    )
    return response.choices[0].message.content # type: ignore


messages = [
    {"role": "system", "content": "You are an expert software engineer that prefers functional programming."},
    {"role": "user", "content": "Write a function to swap the keys and values in a dictionary."}
]

response = generate_response(messages)
print(response)